name: 'Setup go-task/task'
description: 'Setup a go-task/task environment and add it to the PATH'
author: 'Luke Shay'
branding:
  icon: 'clipboard'
  color: 'blue'
runs:
  using: 'node12'
  main: 'bundle.js'