name: '🐛 Bug Report'
description: "If something isn't working as expected 🤔."
title: '[Bug]: '
labels: ['needs triage']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: checkboxes
    id: input1
    attributes:
      label: '💻'
      description: |
        Check this if you would like to implement a PR, we are more than happy to help you go through the process.
      options:
        - label: Would you like to work on this feature?

  - type: textarea
    attributes:
      label: Configuration
      description: Your full GitHub actions configuration

  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what Babel is doing and what you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: 'If you have suggestions on a fix for the bug.'

  - type: textarea
    attributes:
      label: Additional context
      description: 'Add any other context about the problem here. Or a screenshot if applicable.'
