blank_issues_enabled: false
contact_links:
  - name: 🗣 Ask a Question, Discuss
    url: https://github.com/lukeshay/setup-task/discussions
    about: How does X work 🤔? I made this! I have an idea...
