name: PR

on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.
      - run: task --version
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: 'npm'
      - run: npm i
      - run: npm run lint
  prettier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: 'npm'
      - run: npm i
      - run: npm run prettier:check
