name: workflow
on:
  - push
jobs:
  test:
    name: Build and run task
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install task
      uses: ./.

    - run: task --version
